version: "3.8"

networks:
  robinhood:
    driver: bridge
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=post
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=robinhood21
    ports:
      - "5432:5432"
    networks:
      - robinhood
  # app:
  #   container_name: app
  #   build: .
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_DATABASE=post
  #     - DB_USERNAME=postgres
  #     - DB_PASSWORD=robinhood21
  #   networks:
  #     - robinhood
