version: "3.8"

services:
  postgres:
    container_name: post
    image: postgres
    environment:
      - POSTGRES_DB=post
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=robin_hood
    ports:
      - "5432:5432"
  # go:
  #   container_name: api
  #   image:
  #   environment:
  #   ports:
